name: catechism
version: 0.0.14

description: The catechism library is a framework for creating a catechism (question and answer learning tool) application.
homepage: https://github.com/fliturgy/catechism

environment:
  sdk: ^3.3.3

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: 10.7.0
  flutter_localizations:
    sdk: flutter
  go_router: 14.1.0
  flutter_riverpod: 2.5.1

dev_dependencies:
  lints: 4.0.0
  test: ^1.24.3
  flutter_test:
    sdk: flutter
