name: catechism
version: 0.0.16

description: The catechism library is a framework for creating a catechism (question and answer learning tool) application.
homepage: https://github.com/fliturgy/catechism

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.1
  intl: ^0.19.0
  locale_names: ^1.1.1
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: 4.0.0
  test: 1.25.2

flutter:
  generate: true
