name: catechism
version: 0.0.10

description: The catechism library is a framework for creating a catechism (question and answer learning tool) application.
homepage: https://github.com/fliturgy/catechism

environment:
  sdk: '^3.0.2'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  font_awesome_flutter: ^10.4.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  
