name: catechism
version: 0.0.18

description: The catechism library is a framework for creating a catechism (question and answer learning tool) application.
homepage: https://github.com/fliturgy/catechism

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.3.0
  intl: ^0.19.0
  locale_names: ^1.1.1
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.25.7

flutter:
  generate: true
