name: catechism
version: 0.0.12

description: The catechism library is a framework for creating a catechism (question and answer learning tool) application.
homepage: https://github.com/fliturgy/catechism

environment:
  sdk: ^3.1.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: 10.6.0
  flutter_localizations:
    sdk: flutter
  go_router: 13.2.0
  flutter_riverpod: 2.4.10

dev_dependencies:
  lints: 3.0.0
  test: ^1.24.3
  flutter_test:
    sdk: flutter
