name: catechism
version: 0.0.15

description: The catechism library is a framework for creating a catechism (question and answer learning tool) application.
homepage: https://github.com/fliturgy/catechism

environment:
  sdk: 3.4.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: 10.7.0
  flutter_localizations:
    sdk: flutter
  go_router: 14.2.1
  flutter_riverpod: 2.5.1
  intl: 0.19.0

dev_dependencies:
  lints: 4.0.0
  test: 1.25.2
  flutter_test:
    sdk: flutter

flutter:
  generate: true
