name: catechism
version: 0.0.12

description: The catechism library is a framework for creating a catechism (question and answer learning tool) application.
homepage: https://github.com/fliturgy/catechism

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  flutter_localizations:
    sdk: flutter
  go_router: ">=10.0.0 <13.0.0"
  flutter_riverpod: ^2.3.6

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.1
  flutter_test:
    sdk: flutter
